# Application Configuration

# TODO: Switch to a non-root user for database connections for increased security for production
# TODO: Setup HTTPS: Self-Signed SSL, Configure SSL, Create Keystore, Redirect HTTP to HTTPS

# Spring settings
spring:

  # ANSI console output settings
  output:
    ansi:
      enabled: ALWAYS

  # -------------------------
  # Database Connection settings
  # -------------------------
  datasource:
    # Connection URL for the database "SpringRestAPI"
    url: jdbc:mysql://localhost:3306/SpringRestAPI?createDatabaseIfNotExist=true

    # Database username and password
    username: root
    password: root

    # Database driver class name
    driver-class-name: com.mysql.cj.jdbc.Driver

  # -------------------------
  # JPA / Hibernate settings
  # -------------------------
  jpa:
    # Show SQL query log in console
    show-sql: true

    hibernate:
      # Update database schema according to entities
      ddl-auto: update

    properties:
      hibernate:
        # Specific SQL dialect for MySQL 5
        dialect: org.hibernate.dialect.MySQL5Dialect

  # ---------------------------
  # Spring Security settings
  # ---------------------------
  #autoconfigure:
    # Exclude Spring Security Auto Configuration
    #exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration